export const Constants = {
  ERROR_MESSAGE: {
    TARGET_URL_MISSING: `'targetUrl' is missing`,
  },
  MIN_SHORTID_LENGTH: 5,
  MAX_SHORTID_LENGTH: 15,
  HTTP_CODE: {
    CREATED: 201,
  },
  MONGOOSE_ERROR_CODES: {
    DUPLICATED: 11000,
  },
  EVENTS: {
    ADD_TO_REDIRECT: 'ADD_TO_REDIRECT',
    CREATE_REPORT: 'CREATE_REPORT',
  },
}
